version: '3.8'

services:
  financial_rag:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
      - model_cache:/root/.cache/torch/sentence_transformers
      - nltk_data:/root/nltk_data  # Add NLTK data volume
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0  # Fix network binding
      - STREAMLIT_SERVER_PORT=8501
    healthcheck:  # Add healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  model_cache:
    driver: local
  nltk_data:
    driver: local